-- 作品主数据表，同时保护公开读取所需的发布状态约束。
create table projects (
    id bigint generated by default as identity primary key,
    slug varchar(160) not null,
    title varchar(200) not null,
    summary varchar(500) not null,
    description text not null,
    cover_url varchar(1024),
    status varchar(20) not null,
    published_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint projects_slug_unique unique (slug),
    -- 发布状态与发布时间必须保持一致，
    -- 防止公开查询遇到“已发布但没有发布时间”的非法数据。
    constraint projects_status_check check (status in ('DRAFT', 'PUBLISHED')),
    constraint projects_published_at_check check (
        (
            status = 'PUBLISHED'
            and published_at is not null
        )
        or (
            status = 'DRAFT'
            and published_at is null
        )
    )
);
-- 公开列表只查询已发布作品，并按发布时间倒序展示。
-- partial index 避免把草稿纳入公开读取索引。
create index projects_public_order_idx on projects (published_at desc, id desc)
where status = 'PUBLISHED';
comment on table projects is '作品主数据，供公开列表和详情读取';
comment on column projects.id is '数据库内部唯一标识';
comment on column projects.slug is '作品公开访问标识，用于详情地址';
comment on column projects.title is '作品标题';
comment on column projects.summary is '列表展示摘要';
comment on column projects.description is '详情页完整介绍';
comment on column projects.cover_url is '可选封面地址，允许为空';
comment on column projects.status is '发布状态：DRAFT 或 PUBLISHED';
comment on column projects.published_at is '公开发布时间，已发布作品必须有值';
comment on column projects.created_at is '创建时间';
comment on column projects.updated_at is '最后更新时间';
